services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
      - "8787:8787"
    env_file:
      - .env
    networks:
      - red-alumnet

volumes:
  mongo_data:
  postgres_data:

networks:
  red-alumnet:
    driver: bridge
