services:
  db:
    image: postgres:15-alpine
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: kc_user
      POSTGRES_PASSWORD: kc_password
    ports:
      - "8001:5432"
    volumes:
      - postgres_data_kc:/var/lib/postgresql/kc/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - red-alumnet

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: keycloak_server
    env_file:
      - .env
    command: ${KEYCLOAK_COMMAND}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - red-alumnet

volumes:
  postgres_data_kc:
networks:
  red-alumnet:
    driver: bridge
