services:
  mongo:
    image: mongo:7.0
    container_name: mongo_local
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: alum-net
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
