spring:
  application:
    name: alum-net
  datasource:
    url: jdbc:postgresql://localhost:5001/alum-net
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  auth:
    principleAttribute: preferred_username

keycloak:
  client-id: alumnet
  url: http://localhost:8000
  realm: alumnet-realm
  username: develop@alumnet.com
  password: develop

server:
  port: 8200