import { CourseDisplay, ShiftOption } from './types';
export const courses: CourseDisplay[] = [
  {
    id: 1,
    name: 'Art History 101',
    teachersNames: ['Dr. Sarah Davis'],
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-05-15'),
    shift: 'MORNING',
  },
  {
    id: 2,
    name: 'Calculus I',
    teachersNames: ['Prof. Tom Chang'],
    startDate: new Date('2025-01-10'),
    endDate: new Date('2025-05-10'),
    shift: 'AFTERNOON',
  },
  {
    id: 3,
    name: 'Physics for Beginners',
    teachersNames: ['Dr. Nancy Carter'],
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-06-01'),
    shift: 'NIGHT',
  },
  {
    id: 4,
    name: 'Intro to Literature',
    teachersNames: ['Prof. Jane Wilson'],
    startDate: new Date('2025-01-20'),
    endDate: new Date('2025-05-20'),
    shift: 'MORNING',
  },
  {
    id: 5,
    name: 'CS Fundamentals',
    teachersNames: ['Dr. Mike Johnson'],
    startDate: new Date('2026-01-05'),
    endDate: new Date('2026-05-05'),
    shift: 'AFTERNOON',
  },
  {
    id: 6,
    name: 'Data Science Basics',
    teachersNames: ['Dr. Julia White'],
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-07-01'),
    shift: 'NIGHT',
  },
  {
    id: 7,
    name: 'Creative Writing',
    teachersNames: ['Prof. Virginia Woolf'],
    startDate: new Date('2025-02-15'),
    endDate: new Date('2025-06-15'),
    shift: 'MORNING',
  },
  {
    id: 8,
    name: 'Principles of Economics',
    teachersNames: ['Dr. Adam Smith'],
    startDate: new Date('2024-01-25'),
    endDate: new Date('2024-05-25'),
    shift: 'AFTERNOON',
  },
  {
    id: 9,
    name: 'Intro to Psychology',
    teachersNames: ['Dr. Sigmund Freud'],
    startDate: new Date('2026-02-10'),
    endDate: new Date('2026-06-10'),
    shift: 'NIGHT',
  },
  {
    id: 10,
    name: 'Digital Marketing',
    teachersNames: ['Prof. Philip Kotler'],
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-07-01'),
    shift: 'MORNING',
  },
  {
    id: 11,
    name: 'Digital Marketing',
    teachersNames: ['Prof. Philip Kotler'],
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-07-01'),
    shift: 'MORNING',
  },
  {
    id: 12,
    name: 'Digital Marketing',
    teachersNames: ['Prof. Philip Kotler'],
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-07-01'),
    shift: 'MORNING',
  },
  {
    id: 13,
    name: 'Digital Marketing',
    teachersNames: ['Prof. Philip Kotler'],
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-07-01'),
    shift: 'MORNING',
  },
  {
    id: 14,
    name: 'Digital Marketing',
    teachersNames: ['Prof. Philip Kotler'],
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-07-01'),
    shift: 'MORNING',
  },
];

export const SHIFTS: ShiftOption[] = [
  { label: 'Todos los turnos', value: 'all' },
  { label: 'Mañana', value: 'MORNING' },
  { label: 'Tarde', value: 'AFTERNOON' },
  { label: 'Noche', value: 'NIGHT' },
];
