export const courses = [
  {
    id: 1,
    title: 'Art History 101',
    instructor: 'Dr. Sarah Davis',
    status: 'Finalizar',
    color: '#ff6b6b',
    year: 2024,
    shift: 'morning',
    isMyCourse: true,
  },
  {
    id: 2,
    title: 'Calculus I',
    instructor: 'Prof. Tom Chang',
    status: 'Finalizar',
    color: '#4ecdc4',
    year: 2025,
    shift: 'afternoon',
    isMyCourse: false,
  },
  {
    id: 3,
    title: 'Physics for Beginners',
    instructor: 'Dr. Nancy Carter',
    status: 'Finalizar',
    color: '#45b7d1',
    year: 2024,
    shift: 'night',
    isMyCourse: true,
  },
  {
    id: 4,
    title: 'Intro to Literature',
    instructor: 'Prof. Jane Wilson',
    status: 'Detalles',
    color: '#f9ca24',
    year: 2025,
    shift: 'morning',
    isMyCourse: false,
  },
  {
    id: 5,
    title: 'CS Fundamentals',
    instructor: 'Dr. Mike Johnson',
    status: 'Detalles',
    color: '#6c5ce7',
    year: 2026,
    shift: 'afternoon',
    isMyCourse: true,
  },
  {
    id: 6,
    title: 'Data Science Basics',
    instructor: 'Dr. Julia White',
    status: 'Finalizar',
    color: '#a29bfe',
    year: 2024,
    shift: 'night',
    isMyCourse: true,
  },
  {
    id: 7,
    title: 'Creative Writing',
    instructor: 'Prof. Virginia Woolf',
    status: 'Finalizar',
    color: '#fd79a8',
    year: 2025,
    shift: 'morning',
    isMyCourse: false,
  },
  {
    id: 8,
    title: 'Principles of Economics',
    instructor: 'Dr. Adam Smith',
    status: 'Finalizar',
    color: '#00b894',
    year: 2024,
    shift: 'afternoon',
    isMyCourse: true,
  },
  {
    id: 9,
    title: 'Intro to Psychology',
    instructor: 'Dr. Sigmund Freud',
    status: 'Detalles',
    color: '#fdcb6e',
    year: 2026,
    shift: 'night',
    isMyCourse: false,
  },
  {
    id: 10,
    title: 'Digital Marketing',
    instructor: 'Prof. Philip Kotler',
    status: 'Detalles',
    color: '#e17055',
    year: 2025,
    shift: 'morning',
    isMyCourse: true,
  },
  {
    id: 11,
    title: 'Digital Marketing',
    instructor: 'Prof. Philip Kotler',
    status: 'Detalles',
    color: '#e17055',
    year: 2025,
    shift: 'morning',
    isMyCourse: true,
  },
  {
    id: 12,
    title: 'Digital Marketing',
    instructor: 'Prof. Philip Kotler',
    status: 'Detalles',
    color: '#e17055',
    year: 2025,
    shift: 'morning',
    isMyCourse: true,
  },
  {
    id: 13,
    title: 'Digital Marketing',
    instructor: 'Prof. Philip Kotler',
    status: 'Detalles',
    color: '#e17055',
    year: 2025,
    shift: 'morning',
    isMyCourse: true,
  },
  {
    id: 14,
    title: 'Digital Marketing',
    instructor: 'Prof. Philip Kotler',
    status: 'Detalles',
    color: '#e17055',
    year: 2025,
    shift: 'morning',
    isMyCourse: true,
  },
];
export const SHIFTS = [
  { label: 'Todos los turnos', value: 'all' },
  { label: 'Mañana', value: 'morning' },
  { label: 'Tarde', value: 'afternoon' },
  { label: 'Noche', value: 'night' },
];
