export const QUERY_KEYS = {
  getCourses: 'get-courses',
  getUserInfo: 'get-user-info',
  getCourse: 'get-course',
  getUsers: 'get-users',
  getCourseMembers: 'get-course-members',
  getForumPosts: 'get-forum-posts',
  getLibraryLabels: 'get-library-labels',
  getLibraryResources: 'get-library-resources',
  getEventDetails: 'get-event-details',
  getUserActivity: 'get-user-activity',
  getConversations: 'get-conversations',
  getMessages: 'get-messages',
  getAvailableConversations: 'get-available-conversations',
};
