export const QUERY_KEYS = {
  getStudentGrades: 'get-student-grades',
  getCourses: 'get-courses',
  getUserInfo: 'get-user-info',
  getCourse: 'get-course',
  getUsers: 'get-users',
  getCourseMembers: 'get-course-members',
  getForumPosts: 'get-forum-posts',
  getLibraryLabels: 'get-library-labels',
  getLibraryResources: 'get-library-resources',
  getEventDetails: 'get-event-details',
  getUserActivity: 'get-user-activity',
  getConversations: 'get-conversations',
  getMessages: 'get-messages',
  getAvailableConversations: 'get-available-conversations',
  getCourseStudents: 'get-course-students',
  getUnratedEvents: 'get-unrated-events',
  getAutoGrades: 'get-auto-grades',
  getEventStudents: 'get-event-students',
};
